client/src/modules/utils.js
=> FileUtils writes

client/package.json, client/src/index.js, client/src/modules/ui/components/bdsettings.vue, client/src/modules/ui/components/sidebar/Button.vue, client/src/modules/ui/components/sidebar/Header.vue, client/src/modules/ui/components/sidebar/Item.vue, client/src/modules/ui/components/sidebar/Sidebar.vue, client/src/modules/ui/components/sidebar/View.vue, client/src/modules/ui/components/sidebar/index.js, client/webpack.config.js
https://github.com/JsSucks/BetterDiscordApp/issues/9
=> Loaders and components

client/src/modules/ui/components/bdbutton.vue
=> makes BD button look "naturally built in"

core/src/modules/csseditor.js
=> CSS Window opens when ready

client/src/ui/vue.js
=> Fix tooltip positioning

client/src/styles/partials/bdsettings/plugincard.scss, client/src/styles/partials/generic/forms.scss, client/src/ui/components/bd/pluginsetting/File.vue, client/src/ui/components/bd/pluginsetting/PluginSetting.vue, core/src/main.js, tests/plugins/Example/config.json
Uses a native open dialog to select a file/files. Value will be set to an array containing the selected file paths.
=> Add file setting

client/src/styles/partials/generic/modals.scss
Backdrop animation was deleted in a merge.
=> Fix modal backdrop animation

client/src/styles/partials/generic/forms.scss, client/src/ui/components/bd/pluginsetting/Dropdown.vue, client/src/ui/components/bd/pluginsetting/Number.vue, client/src/ui/components/bd/pluginsetting/PluginSetting.vue, client/src/ui/components/bd/pluginsetting/Radio.vue, tests/plugins/Example/config.json
=> Add Number, Radio and Dropdown setting types

client/src/styles/partials/generic/forms/sliders.scss, client/src/ui/components/bd/pluginsetting/Slider.vue, tests/plugins/Example/config.json
=> Add preset points along a slider

client/src/styles/partials/bdsettings/button.scss, client/src/styles/partials/bdsettings/sidebarview.scss, client/src/styles/partials/discordoverrides.scss
BetterDiscord currently looks like this on macOS:
=> macOS and Linux fixes

client/src/modules/thememanager.js, tests/themes/Example/config.json, tests/themes/Example/index.scss, tests/themes/Example/vars.scss
all current settings functional for themes?
=> Theme settings

client/src/modules/thememanager.js, client/src/ui/components/bd/pluginsetting/Dropdown.vue, client/src/ui/components/bd/pluginsetting/Radio.vue, tests/plugins/Example/config.json, tests/themes/Example/config.json
You might have to delete user configs
=> Change dropdown/radio structure

client/src/modules/extmodule.js, client/src/modules/plugin.js, client/src/modules/theme.js, client/src/structs/settings/settingsset.js, client/src/structs/settings/types/array.js, client/src/structs/settings/types/basesetting.js, client/src/structs/settings/types/number.js, client/src/structs/settings/types/slider.js, client/src/ui/components/bd/setting/Number.vue, client/src/ui/components/bd/setting/Slider.vue
Also changed plugin/theme event emitters to AsyncEventEmitter.
=> Fix settingsset.findSetting and arraysetting.items

client/src/builtin/EmoteComponent.vue, client/src/builtin/EmoteModule.js, client/src/modules/discordapi.js, client/src/modules/eventhook.js, client/src/modules/modules.js, client/src/modules/patcher.js, client/src/modules/pluginapi.js, client/src/modules/reactcomponents.js, client/src/modules/vendor.js, client/src/modules/webpackmodules.js, client/src/ui/components/common/Autocomplete.vue
Should fix all autocomplete bugs and make emotes work with ;; wrapper
=> Emote changes and minor stuff

client/src/data/user.settings.default.json, client/src/index.js, client/src/structs/settings/setting.js, client/src/structs/settings/types/array.js, client/src/structs/settings/types/guild.js, client/src/styles/partials/generic/forms/guilds.scss, client/src/styles/partials/generic/forms/index.scss, client/src/styles/partials/generic/forms/main.scss, client/src/ui/components/bd/setting/Guild.vue, client/src/ui/components/bd/setting/Setting.vue, common/modules/utils.js, tests/plugins/Example 4/config.json
=> Add guild setting

client/src/modules/reactcomponents.js
Patches guild text/voice channels seperately and adds direct message channels.
=> Channel components

client/src/structs/settings/setting.js, client/src/structs/settings/types/collection.js, client/src/ui/components/bd/setting/Collection.vue
Extends array settings to create Settings instead of SettingsSets for collection settings.
=> Extend ArraySetting for collections

client/src/modules/reactcomponents.js
This was done using the same process as their internal one, we couldn't just patch the module prototype since the module is already in place and has re-bound functions added to listeners before we load.
=> Add temporary .bd file check on drop

client/src/builtin/E2EE.js, client/src/builtin/E2EEComponent.vue, client/src/builtin/E2EEMessageButton.vue, client/src/styles/partials/bdsettings/e2ee.scss
=> Add clicking the status icon to toggle encryption and add an indicator to encrypted messages

client/src/data/user.settings.default.json, client/src/modules/patcher.js, client/src/modules/pluginapi.js, client/src/styles/partials/bdsettings/button.scss, client/src/styles/partials/bdsettings/index.scss, client/src/styles/partials/generic/forms/collections.scss, client/src/styles/partials/generic/forms/index.scss, client/src/ui/classnormaliser.js, client/src/ui/components/BdSettingsWrapper.vue, client/src/ui/components/bd/setting/Collection.vue, client/src/ui/components/bd/setting/Setting.vue, client/src/ui/toasts.js, gulpfile.babel.js, package.json
=> Add an option to disable toasts and additional options for collections

package.json, scripts/inject.js
adds an inject script so we can inject without needing to manually do it.
install to stable with `npm run inject`
to canary with `npm run inject canary`
to ptb with `npm run inject ptb`
=> Add inject script

client/src/styles/partials/bdsettings/button.scss, client/src/styles/partials/bdsettings/sidebarview.scss, client/src/styles/partials/generic/drawers.scss, client/src/styles/partials/generic/forms/switches.scss, client/src/styles/partials/sidebarview/sidebar.scss
I just felt like some stuff could be smoother and have lighter animations on the CPU.
lil preview: https://streamable.com/68zbh
=> Fixed a bunch of transitions and changed the arrow animation.
